---
- name:   First Basic Playbook created by Narendra Kushwaha
  hosts:  localhost

  tasks:
  - name: Test Connectivity
    ping:

  - name: "Print Output dddfdf"
    debug: msg="Alright!!"
